name: GitHub Actions Demo
run-name: ${{ github.actor }} made a pull request to explorers ğŸš€
on: [pull_request]
jobs:
  test-json-structure:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ triggered by a ${{ github.event_name }} event."
